import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { z } from "zod";

// This directory and the ./integrations/* package exports are generated together.
// --root supports checking another checkout without changing the current one.
const args = process.argv.slice(2);
const rootIndex = args.indexOf("--root");
const root =
  rootIndex === -1
    ? path.resolve(import.meta.dirname, "..")
    : path.resolve(args[rootIndex + 1]);
const check = args.includes("--check");
const packageRoot = path.join(root, "packages/blume");
const packagePath = path.join(packageRoot, "package.json");
const require = createRequire(packagePath);
const registryPath = require.resolve("@c15t/integrations/registry");
let sdkRoot = path.dirname(registryPath);
while (true) {
  const candidate = path.join(sdkRoot, "package.json");
  if (
    existsSync(candidate) &&
    JSON.parse(readFileSync(candidate, "utf-8")).name === "@c15t/integrations"
  ) {
    break;
  }
  const parent = path.dirname(sdkRoot);
  if (parent === sdkRoot) {
    throw new Error(
      "Cannot locate the installed @c15t/integrations package manifest."
    );
  }
  sdkRoot = parent;
}
const sdk = JSON.parse(
  readFileSync(path.join(sdkRoot, "package.json"), "utf-8")
);
const manifest = JSON.parse(readFileSync(packagePath, "utf-8"));
const publicPaths = Object.entries(sdk.exports)
  .filter(
    ([name, target]) =>
      name !== "." &&
      name !== "./package.json" &&
      !name.includes("*") &&
      target !== null
  )
  .map(([name]) => {
    if (!/^\.\/[a-z0-9]+(?:[-/][a-z0-9]+)*$/u.test(name)) {
      throw new Error(
        `Unsupported c15t export ${name}; review its public API before re-exporting it.`
      );
    }
    return name.slice(2);
  })
  .toSorted();
const generated = Object.fromEntries(
  publicPaths.map((name) => [
    `./integrations/${name}`,
    // Export conditions are ordered: TypeScript must match before default.
    Object.fromEntries([
      ["types", `./dist/types/integrations/${name}.d.ts`],
      ["default", `./src/integrations/${name}.ts`],
    ]),
  ])
);
const exports = Object.fromEntries(
  Object.entries(manifest.exports).filter(
    ([name]) => !name.startsWith("./integrations/")
  )
);
const expectedExports = { ...exports, ...generated };
const drift: string[] = [];
if (
  JSON.stringify(Object.entries(manifest.exports).toSorted()) !==
  JSON.stringify(Object.entries(expectedExports).toSorted())
) {
  drift.push("packages/blume/package.json exports");
}
const directory = path.join(packageRoot, "src/integrations");
if (!check) {
  mkdirSync(directory, { recursive: true });
}
const expectedFiles = new Set(publicPaths.map((name) => `${name}.ts`));
for (const file of existsSync(directory)
  ? readdirSync(directory, { recursive: true })
  : []) {
  if (
    file.endsWith(".ts") &&
    !expectedFiles.has(file.replaceAll(path.sep, "/"))
  ) {
    drift.push(`src/integrations/${file}`);
    if (!check) {
      rmSync(path.join(directory, file));
    }
  }
}
for (const name of publicPaths) {
  const file = path.join(directory, `${name}.ts`);
  const expected = `// Generated by bun run sync:c15t-integrations. Do not edit.\nexport * from "@c15t/integrations/${name}";\n`;
  if (!existsSync(file) || readFileSync(file, "utf-8") !== expected) {
    drift.push(`src/integrations/${name}.ts`);
    if (!check) {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, expected);
    }
  }
}
// A registry entry's consent category is a category name or, for vendors that
// need a combination, a condition such as Sentry's `{ or: [...] }`.
type ConsentCondition =
  | { kind: "category"; name: string }
  | { kind: "and" | "or"; terms: ConsentCondition[] }
  | { kind: "not"; term: ConsentCondition };
const consentCondition: z.ZodType<ConsentCondition, unknown> = z.lazy(() =>
  z.union([
    z.string().transform((name) => ({ kind: "category" as const, name })),
    z
      .object({ and: z.array(consentCondition) })
      .transform(({ and }) => ({ kind: "and" as const, terms: and })),
    z
      .object({ or: z.array(consentCondition) })
      .transform(({ or }) => ({ kind: "or" as const, terms: or })),
    z
      .object({ not: consentCondition })
      .transform(({ not }) => ({ kind: "not" as const, term: not })),
  ])
);
const registryEntries = z.array(
  z.object({
    consentCategory: consentCondition,
    label: z.string(),
    packageSubpath: z.string(),
  })
);
const formatCondition = (
  condition: ConsentCondition,
  nested = false
): string => {
  switch (condition.kind) {
    case "category": {
      return `\`${condition.name}\``;
    }
    case "not": {
      return `not ${formatCondition(condition.term, true)}`;
    }
    default: {
      const text = condition.terms
        .map((term) => formatCondition(term, true))
        .join(` ${condition.kind} `);
      return nested ? `(${text})` : text;
    }
  }
};
// Keep the rendered page and Markdown/agent mirrors on the same static catalog.
const docsPath = path.join(
  root,
  "apps/docs/content/docs/configuration/integrations.mdx"
);
if (existsSync(docsPath)) {
  const { builtInScriptIntegrations } = await import(
    pathToFileURL(registryPath).href
  );
  const start = "{/* c15t-integrations:start */}";
  const end = "{/* c15t-integrations:end */}";
  const document = readFileSync(docsPath, "utf-8");
  if (!document.includes(start) || !document.includes(end)) {
    throw new Error(
      "Integration guide is missing its generated catalog markers."
    );
  }
  const rows = registryEntries.parse(builtInScriptIntegrations).map((entry) => {
    if (!publicPaths.includes(entry.packageSubpath)) {
      throw new Error(
        `Registry integration ${entry.packageSubpath} has no named public SDK export.`
      );
    }
    return `| ${entry.label} | \`blume/integrations/${entry.packageSubpath}\` | ${formatCondition(entry.consentCategory)} |`;
  });
  const table = [
    "| Integration | Import path | Default consent category |",
    "| --- | --- | --- |",
    ...rows,
  ].join("\n");
  const expected = `${document.slice(0, document.indexOf(start) + start.length)}\n\n${table}\n\n${document.slice(document.indexOf(end))}`;
  if (expected !== document) {
    drift.push("integration documentation catalog");
    if (!check) {
      writeFileSync(docsPath, expected);
    }
  }
}
if (check && drift.length > 0) {
  console.error(
    `c15t script exports are out of date:\n${drift.map((file) => `  ${file}`).join("\n")}\nRun bun run sync:c15t-integrations and commit the generated changes.`
  );
  process.exitCode = 1;
} else if (!check && drift.length > 0) {
  manifest.exports = expectedExports;
  writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
}
